'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LoLRememberV.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property BirTik() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BirTik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property BirTik2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BirTik2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property İkiTik() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("İkiTik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property İkiTik2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("İkiTik2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T111() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T112() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T211() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T211", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T212() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T212", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T33() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream öğesine benzeyen System.IO.UnmanagedMemoryStream türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property T44() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T44", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
